service: serverless-shortlinker-api

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

  httpApi:
    cors: true
    authorizers:
      customAuthorizerUsers:
        type: request
        functionName: authorizerUsers

  environment:
    USERS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-USERS_TABLE
    LINKS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-LINKS_TABLE
    #DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

    #https://udhcf9fhw2.execute-api.eu-central-1.amazonaws.com/links/d0f280
    BASE_URL: !GetAtt HttpApi.ApiEndpoint

    # SQS_DEACTIVATION_QUEUE_URL: !Ref DeactivationQueue

    SECRET_ACCESS_TOKEN: ${file(./secrets.json):SECRET_ACCESS_TOKEN}
    SECRET_REFRESH_TOKEN: ${file(./secrets.json):SECRET_REFRESH_TOKEN}
    SES_EMAIL: ${file(./secrets.json):SES_EMAIL}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - 'arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_TABLE}'
            - 'arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.LINKS_TABLE}'
            # - 'arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'
            # - { 'Fn::GetAtt': ['TableUsers', 'Arn'] }
            # - { 'Fn::GetAtt': ['TableLinks', 'Arn'] }

functions:
  authorizerUsers:
    handler: src/functions/authorizer.users

  signUp:
    handler: src/functions/auth.signUp
    events:
      - httpApi:
          path: /auth/sign-up
          method: post

  signIn:
    handler: src/functions/auth.signIn
    events:
      - httpApi:
          path: /auth/sign-in
          method: post

  usersList:
    handler: src/functions/auth.usersList
    events:
      - httpApi:
          path: /auth/list
          method: get

  createNewLink:
    handler: src/functions/links.createNewLink
    events:
      - httpApi:
          path: /links/create-new-link
          method: post
          authorizer:
            name: customAuthorizerUsers

  linksList:
    handler: src/functions/links.linksList
    events:
      - httpApi:
          path: /links/list
          method: get
          authorizer:
            name: customAuthorizerUsers

  redirectToOriginalLink:
    handler: src/functions/links.redirectToOriginalLink
    events:
      - httpApi:
          path: /links/{linkMarker}
          method: get

  deactivateLink:
    handler: src/functions/links.deactivateLink
    events:
      - httpApi:
          path: /links/deactivate/{linkID}
          method: patch

  deactivateLinkCron:
    handler: src/functions/links.deactivateLinkCron
    events:
      # - schedule: "cron(0 0 * * *)"
      - httpApi:
          path: /links/deactivate
          method: get

  # ses-services:
  #   handler: src/services/ses.sendEmailsForDeactivatedLinks
  #   event:
  #     - sqs:
  #         arn: !GetAtt DeactivationQueue.Arn
  #         batchSize: 10

resources:
  Resources:
    TableUsers:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}

        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S

        KeySchema:
          - AttributeName: userID
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    TableLinks:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.LINKS_TABLE}

        AttributeDefinitions:
          - AttributeName: linkID
            AttributeType: S

        KeySchema:
          - AttributeName: linkID
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # DeactivationQueue:
    #   Type: AWS::SQS::Queue
    #   Properties:
    #     QueueName: deactivation-queue
    #     VisibilityTimeout: 900
    #     MessageRetentionPeriod: 86400
